spring.application.name=walkingapi
spring.datasource.url=jdbc:mysql://mysql-3c031966-alsdud6385-0f28.l.aivencloud.com:13731/WalkingDB?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080
